version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    volumes:
        - ./.docker/elasticsearch/esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - elk

  # logstash:
  #   image: logstash:7.14.2
  #   container_name: logstash
  #   hostname: logstash
  #   ports:
  #     - "8089:8089"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:logstash
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: